# Generated by Django 5.2.6 on 2025-09-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pattern_url', models.URLField(blank=True)),
                ('bType', models.CharField(choices=[('A', 'Alpha'), ('N', 'Normal'), ('M', 'Macreme')], default='N', max_length=1)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('numColors', models.IntegerField(blank=True, null=True)),
                ('bLength', models.CharField(choices=[('AC', 'Airpod case'), ('A', 'Anklet'), ('BE', 'Belt'), ('B', 'Bracelet'), ('BM', 'Bookmark'), ('CS', 'Chapstick holder'), ('C', 'Choker'), ('H', 'Hairpiece'), ('K', 'Keychain'), ('P', 'Patch'), ('W', 'Wallhanging'), ('U', 'Unknown')], default='B', max_length=2)),
                ('numStrings', models.IntegerField()),
                ('goingWhere', models.CharField(choices=[('K', 'Keeping'), ('GI', 'Giving away'), ('GA', 'Gave away'), ('SE', 'Selling'), ('SO', 'Sold'), ('U', 'Unknown')], default='K', max_length=2)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
