# Generated by Django 5.2.6 on 2025-10-02 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('caption', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BraceletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracelet_backend.bracelet')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracelet_backend.image')),
            ],
        ),
    ]
