# Generated by Django 5.2.6 on 2025-10-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0002_image_braceletimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='bracelets/'),
        ),
    ]
