# Generated by Django 5.2.6 on 2025-10-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0003_bracelet_order_image_order_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bracelet',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
    ]
