# Generated by Django 5.2.6 on 2025-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0004_alter_bracelet_options_alter_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
