# Generated by Django 5.2.6 on 2025-10-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0005_alter_bracelet_order_alter_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='favorite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
