# Generated by Django 5.2.6 on 2025-10-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0006_image_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='favorite',
            field=models.BooleanField(blank=True),
        ),
    ]
