# Generated by Django 5.2.6 on 2025-11-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0007_alter_image_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
    ]
