# Generated by Django 5.2.6 on 2025-11-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0009_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
