# Generated by Django 5.2.6 on 2026-02-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet_backend', '0010_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='favorite',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
